# Generated by Django 3.0.8 on 2023-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('openId', models.CharField(max_length=200, unique=True)),
                ('nickname', models.CharField(max_length=200)),
                ('avatarUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
