# Generated by Django 3.0.8 on 2023-06-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20230603_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
