# Generated by Django 3.0.8 on 2023-07-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=200, unique=True)),
                ('UserGameDetail', models.CharField(max_length=200)),
                ('PkHistoryList', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
