# Generated by Django 3.0.8 on 2023-09-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0006_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
