# Generated by Django 3.0.8 on 2023-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0007_auto_20230901_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HardLevelStep',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
