# Generated by Django 3.0.8 on 2023-09-04 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0008_user_hardlevelstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
