# Generated by Django 3.0.8 on 2023-09-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0009_user_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
